# Apply settings to the whole workspace
workspace = true

# General settings
consolidate-commits = true
sign-commit = false
sign-tag = false
push = true
tag = true
publish = true
allow-branch = ["main"]
generate-release-notes = true
dependent-version = "upgrade" # upgrade version for dependent crates

[release]
changelog = "CHANGELOG.md"
update-workspace-dependencies = true

[git]
push-remote = "origin"
enable-github-release = true
github-token = "${GITHUB_TOKEN}"

[packages.klirr-render]
tag-name = ""

[packages.klirr-core]
tag-name = ""
